## try~ except~ finally

```python
try:
    print('Blue')
    print(Deep Blue)
except:
    print('Deep Blue is not printed')
finally:
    print('finally must be printed')
    
Deep Blue가 정의되지 않아 에러가 발생해서 except이 실행되고 finally는 반드시 실행됩니다.
```

